### ISSUE TITLE
Excluding Files

### ISSUE THREAD

**Issue by jrevillard** [arillso/ansible.restic#12]
Hi,

Would it be possible to expose the "filter" functionality as described here: https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files ?

Best,
Jerome

**Comment by mleutenegger** [comment]
Hi, 

it should be possible to include such a feature. The way I see it, the solution would be to add 2 config variables to the repo: 
- `restic_exclude_cache` (Bool)
- `restic_exclude` (Dict)

`restic_exclude_cache ` Would add the `— exclude-caches` flag and `restic_exclude` allows adding filepaths in this way:
```yaml
restic_exclude:
  - path: /path/to/exclude1
    kind: exclude # default
  - path: /path/to/exclude2
    kind: iexclude
  - path: /path/to/exclude3
    kind: exclude-file
  - path: /path/to/exclude2
    kind: exclude-if-present

```
These would then be added as arguments to the backup.

@sbaerlocher your opinion?

**Comment by mleutenegger** [comment]
On second thought, it might be better to separate the `—exclude-file` arg to not mix the ideas of „exclude this file“ and „exclude all files listed in this file. We would then additionally add
- `exclude_from_file` (Array)
Which allows adding files to check for filenames to omit.

**Comment by sbaerlocher** [comment]
Would a Key vaule list be another solution?

```yml
exclude:
  exclude:
    - /path/to/exclude1
  iexclude:
    - path: /path/to/exclude2
  exclude-file:
    - path: /path/to/exclude3
```
