### ISSUE TITLE
distribution tasks skipped due to undefined name in restic_backups

### ISSUE THREAD

**Issue by whysthatso** [arillso/ansible.restic#23]
this is the var block in the host's var file:

```
restic_version: '0.11.0'
restic_repos:
  b2:
    name: b2
    location: b2:foobar:/name_of_backup
    password: "{{ vault_restic_pass_b2 }}"
    init: true
    b2_account_id: "{{ vault_b2_account_id }}"
    b2_account_key: "{{ vault_b2_account_key }}"
restic_backups:
  foobar:
    name: foobar
    repo: b2
    src: /path/to/dir
    scheduled: true
    schedule_hour: 3
restic_create_cron: true
restic_dir_owner: root
restic_dir_group: root
```
when i remove all the condtions on the Linux.yml task "Create backup credentials", i get the following error:

```
The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'
```

am i somehow setting these hashes and lists wrong?

**Comment by mleutenegger** [comment]
Hi @whysthatso, try to switch the `backups` definition from a dict to a list:
```
restic_backups:
  - name: foobar
    repo: b2
    src: /path/to/dir
    scheduled: true
    schedule_hour: 3
```
