### ISSUE TITLE
Multiple source folders in single backup

### ISSUE THREAD

**Issue by rxcket** [arillso/ansible.restic#33]
It would be nice to specify multiple source folders in a single backup like this

```
restic_backups:
  data:
    name: data
    repo: remove
    src:
      - /path/to/data
      - /path/to/data123
      - /path/to/other/data

**Comment by mleutenegger** [comment]
Intresting thought to have the option to specify multiple backups. What would be the main benefit of using this over specifying multiple backups to the same repository?

The way I see it,
```yaml
restic_backups:
  data:
    name: data
    repo: remove
    src:
      - /path/to/data
      - /path/to/data123
      - /path/to/other/data
```
would be identical to 
```yaml
restic_backups:
  data:
    name: data
    repo: remove
    src: /path/to/data
  data123:
    name: data123
    repo: remove
    src: /path/to/data123
  otherdata:
    name: otherdata
    repo: remove
    src: /path/to/other/data
```
