### ISSUE TITLE
Add hook for error

### ISSUE THREAD

**Issue by ptoulouse** [arillso/ansible.restic#51]
Would it be possible to have hooks to run different set of command depending on the success or failure of a backup?

Something like this overly simplified example:

```
locations:
  my-location:
    from: /data
    to: my-backend
    hooks:
      before:
        - echo "Starting backup"
      after:
        - echo "Backup completed"
      success:
        - echo "Backup successful"
      failure:
        - echo "Backup failed"
```
